apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.notificationService.replicaCount }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: "{{ .Values.notificationService.image.repository }}:{{ .Values.notificationService.image.tag }}"
          imagePullPolicy: {{ .Values.notificationService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.notificationService.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.notificationService.service.port }}"
