name: PayStream Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full git commit history layers

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python Dependencies
        run: |
          cd payment-service/payment-service || cd payment-service
          pip install -r requirements.txt

      - name: Scan Code for Secrets (TruffleHog)
        uses: trufflesecurity/trufflehog@main
        with:
          base: "" # FIX: Forces a complete scan of all workspace assets instead of comparing changes

      - name: Vulnerability Static Scanning (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'HIGH,CRITICAL'
